import { Tenant } from "./types";

export const tenants: Tenant[] = [
  {
    id: "t1",
    name: "Cheepy",
    slug: "cheepy",
    domain: "cheepy.ru",
    logo: "🛍️",
    currency: "RUB",
    commission: 12,
    regions: ["Москва", "Санкт-Петербург", "Казань", "Новосибирск", "Екатеринбург"],
    status: "active",
    sellersCount: 245,
    usersCount: 18400,
    productsCount: 12500,
    createdAt: "2023-03-15",
  },
  {
    id: "t2",
    name: "FashionBox",
    slug: "fashionbox",
    domain: "fashionbox.ru",
    logo: "👗",
    currency: "RUB",
    commission: 15,
    regions: ["Москва", "Краснодар", "Ростов-на-Дону"],
    status: "active",
    sellersCount: 89,
    usersCount: 5200,
    productsCount: 4300,
    createdAt: "2024-01-10",
  },
  {
    id: "t3",
    name: "SportZone",
    slug: "sportzone",
    domain: "sportzone.ru",
    logo: "🏃",
    currency: "RUB",
    commission: 10,
    regions: ["Москва"],
    status: "setup",
    sellersCount: 12,
    usersCount: 340,
    productsCount: 680,
    createdAt: "2025-01-20",
  },
];
